include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    unused_import: ignore
    
linter:
  rules:
    avoid_print: false
    avoid_types_as_parameter_names: false
    use_build_context_synchronously: false
    use_super_parameters: false
    file_names: false
    unnecessary_brace_in_string_interps: false
    curly_braces_in_flow_control_structures: false
    prefer_interpolation_to_compose_strings: false
    sort_child_properties_last: false
    unnecessary_to_list_in_spreads: false
